functions:
  static:
    handler: src/server/index.staticFile
    events:
      - http:
          path: /public/{proxy+}
          method: get
  ping:
    description: Ping the service 
    handler: src/server/index.ping
    events:
      - http:
          path: ping
          method: get
  application:
    description: React Isomorphic Application 
    handler: src/server/index.application
    warmup: true
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{proxy+}
          method: get