functions:
  graphql:
    description: GraphQL Interface 
    handler: src/graphql/index.handler
    events:
      - http:
          path: /graphql
          method: post
      - http:
          path: /graphql
          method: get