functions:
  auth_google:
    description: Google Auth 2.0 Login
    handler: src/auth/index.auth_google
    warmup: true
    events:
      - http:
          path: /auth/google/{any+}
          method: ANY
  auth_development:
    description: Google Auth 2.0 Login
    handler: src/auth/index.auth_development
    warmup: true
    events:
      - http:
          path: /auth/development/{any+}
          method: ANY